name: Foraldradagar
options:
  bundleIdPrefix: com.foraldradagar
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_ALLOWED: false

targets:
  Foraldradagar:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: DesignSystem
      - path: Models
      - path: Services
      - path: Views
      - path: Onboarding
      - path: Assets.xcassets
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foraldradagar.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: "Föräldradagar"
        SWIFT_STRICT_CONCURRENCY: minimal
